server:
  port: 9898
#zipkin:
#  collector:
#    rabbitmq:
#      addresses: localhost:5672
#      password: guest
#      username: guest
#      queue: zipkin


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 配置运行schema.sql的连接
    schema-username: root
    schema-password: root
    # 配置运行data.sql的连接
    data-username: root
    data-password: root
    platform: mysql
    schema: classpath:schema.sql
    # data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always

